#1 init app
Werton-Wad/dev-inc-tic-tac-toe pull request #1
Opened 2020-10-26 21:16 UTC by Werton-Wad

2020-10-26 22:31 UTC, VadimAlkhimenok reviewed
Hi! I left some comments. You can fix it. Good game. Well done!

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ButtonReset/index.js
> +        <button className="button-reset" onClick={ props.handleClick }>reset</button>
You can use destructuring. For example: instead of `(props)` write `({ handleClick })` and then `onClick={ handleClick }`.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ButtonTryAgain/index.js
> +const ButtonTryAgain = (props) => {
The same. Use destructuring

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ButtonTryAgain/index.js
> +export default ButtonTryAgain;
You can write `export const ButtonTryAgain = (props) => {}` instead of `export default ButtonTryAgain; `

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ButtonUndo/index.js
> +}
All your buttons the same. I think you can create one button and give properties as  `handleClick`, `name`...

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/Cell/index.js
> +    const { handleClickCell, number, cells } = props;
Use destructuring.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/Cell/index.js
> +            </div>
Align `<div className="cell-content">`.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ListCells/index.js
> +    const { handleClickCell, cells } = props;
Use destructuring.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/StartMenu/index.js
> +    const { handleComputerMode, handleChoosePlayer, player } = props;
Use destructuring.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +        const winner = utilis.calculateWinner(this.state.cells);
You can take all the values you need from this.state through destructuring.
For example: `const {cells} = this.state;`

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +        cells[i] = this.state.isNext ? 'X' : 'O';
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +            if (this.state.computerMode) setTimeout(this.handleComputerMove, 400);
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +        const winner = utilis.calculateWinner(this.state.cells);
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +        const computerMove = utilis.computerMove(this.state.cells);
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +            cells[this.state.lastMove] = null;
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +        cells[this.state.lastMove] = null;
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +        const isFilledCells = utilis.checkArr(this.state.cells);
Take all the values you need.

2020-10-26 22:31 UTC, VadimAlkhimenok commented on src/components/ticTacToeApp/index.js
> +            utilis.colorWinCells(this.state.cells, winner.winnerCoord);
Take all the values you need.

2020-10-27 09:17 UTC, artur-nikitsin reviewed
Hello! Great game! I left some comments.

2020-10-27 09:17 UTC, artur-nikitsin commented on src/components/StartMenu/index.js
> +                        <input type="radio" name="player" value='O' id="checkO" onChange={(e) => handleChoosePlayer(e, e.target.value)} />
The handler will have access to the event. You can destructure the data there and write simply:
`onChange={handleChoosePlayer}`

2020-10-27 09:17 UTC, artur-nikitsin commented on src/components/StartMenu/index.js
> +                <div className="playmode" onClick={() => handleComputerMode(false)}>
You can write simply:
`onClick={handleComputerMode}`
and use HOF  with this syntax for ex :
`const handleComputerMode =(bool)=>()=>{"magic with bool"}`

2020-10-27 09:17 UTC, artur-nikitsin commented on src/components/StartMenu/modal-window.css
> +    height: 300px; /* 35% */
Remove unused comments

2020-10-27 16:28 UTC, maximsan requested changes
Hello! Looks great! I left some comments, don't forget to resolve them. Good work!

2020-10-27 16:28 UTC, maximsan commented on src/components/ButtonTryAgain/index.js
> +export default ButtonTryAgain;
Actually, it has no big sense here

2020-10-27 16:28 UTC, maximsan commented on src/components/ButtonUndo/index.js
> +}
Yep, no need to copy-paste the same code, use one button everywhere

2020-10-27 16:28 UTC, maximsan commented on src/components/ListCells/index.js
> +            { cells.map((_, i) => <Cell key={i}
Don't use method index as a key

2020-10-27 16:28 UTC, maximsan commented on src/index.css
> +
don't keep empty files

2020-10-27 16:28 UTC, maximsan commented on src/config/index.js
> +const soundEndGame = 'http://soundbible.com/mp3/shooting_star-Mike_Koenig-1132888100.mp3';
we will use .env for this in the project, for now it's fine

2020-10-27 16:28 UTC, maximsan commented on src/components/utilis/index.js
> +    if (!cells[i]) blankCells.push(i);
I prefer to be explicit, it looks shorter, but it's better to wrap code in brackets in conditions

2020-10-27 16:28 UTC, maximsan commented on src/components/utilis/index.js
> +  const $cells = document.querySelectorAll('.cell');
we don't use document selectors in React, it's caused huge performance impact, and we don't use names with $ sign as in jQuery

2020-10-28 12:52 UTC, Werton-Wad commented
Resolved

2020-10-28 12:52 UTC, closed without merging